# Generated by Django 4.2.1 on 2023-05-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTeams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidos',
            name='creado',
        ),
        migrations.AddField(
            model_name='partidos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADO', 'Programado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20),
        ),
    ]
